-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 16, 2018 at 03:18 PM
-- Server version: 10.1.21-MariaDB
-- PHP Version: 7.1.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sp_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `dog_breeds`
--

CREATE TABLE `dog_breeds` (
  `breed_id` int(11) NOT NULL,
  `breed_name` varchar(32) NOT NULL,
  `breed_description` varchar(1000) NOT NULL,
  `breed_image` varchar(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `dog_breeds`
--

INSERT INTO `dog_breeds` (`breed_id`, `breed_name`, `breed_description`, `breed_image`) VALUES
(0, 'Chihuahua', 'The Chihuahua dog breed‘s charms include his small size, outsize personality, and variety in coat types and colors. He’s all dog, fully capable of competing in dog sports such as agility and obedience, and is among the top 10 watchdogs recommended by experts. He loves nothing more than being with his people and requires a minimum of grooming and exercise.', 'Chihuahua.jpg'),
(1, 'Japanese Chin/Spaniel', 'The Japanese Chin dog breed hails from Asia, where he has been prized as a companion for more than a thousand years. He was a popular member of Chinese and Japanese imperial courts, and it was in Japan that his distinctive look was developed. This breed is elegant and dainty, mild-mannered and playful.', 'Japanese_Spaniel.jpg'),
(2, 'Maltese', 'A dog breed who’s gentle and fearless, the Maltese greets everyone as a friend. His glamorous white coat gives him a look of haughty nobility, but looks can be deceiving. This is a sprightly, vigorous dog who excels not only as a companion but also as a therapy dog and competitor in such dog sports as agility, obedience, rally, and tracking. But most of all, he loves to be with his people.', 'Maltese.jpg'),
(3, 'Pekinese', 'Pekinese were dogs bred for centuries to be the cherished companions of the imperial family of China. Today they are still cherished family companions and show dogs who greet everyone they meet with dignity and grace.', 'Pekinese.jpg'),
(4, 'Shih', 'His name means little lion, but thereâ€™s nothing fierce about this dog breed. The Shih Tzu is a lover, not a hunter. Bred solely to be a companion, the Shih Tzu is an affectionate, happy, outgoing housedog who loves nothing more than to follow his people from room to room. In recent years, however, owners have started taking the Shih Tzu off their laps and into dog sports, training him for obedience, rally, and agility competitions.\r', 'Shih.jpg'),
(5, 'Blenheim Spaniel', 'Although heâ€™s born to be a companion, the Blenheim Spaniel, also called Cavalier King Charles Spaniel dog breed, retains the sporty nature of his spaniel ancestors. If heâ€™s not sitting on a lap or getting a belly rub, nothing makes him happier than to flush a bird and then attempt to retrieve it. One of the largest of the toy breeds, heâ€™s often as athletic as a true sporting breed and enjoys hiking, running on the beach, and dog sports such as agility, flyball and rally. Some have even shown their prowess as hunting dogs. The more restful members of the breed find success as family friends and therapy dogs.\r', 'Blenheim_Spaniel.jpg'),
(6, 'Papillon', 'The Papillon dog breed descends from the toy spaniels that are frequently portrayed in paintings by the Old Masters, from as far back as the 16th century. Heâ€™s highly active and is a wonderful competitor in agility and obedience. His sparkling personality makes him a favorite of all who meet him.\r', 'Papillon.jpg'),
(7, 'Toy Terrier', 'Originally created as smaller versions of their larger Smooth Fox Terrier dog breed ancestors, Toy Fox Terriers have been used for a variety of tasks, serving as ratters on farms and as hunters of small game such as squirrel. They have been successful circus dogs and performers and their intelligence helps them to do well in obedience and agility competitions. Their most important purpose, however, is to be a loyal, loving, and devoted companion that amuses and entertains their families\r', 'Toy_Terrier.jpg'),
(8, 'Rhodesian Ridgeback', 'This handsome dog breed was created in Africa to be a versatile hunter and home guardian. Heâ€™s smart but sometimes stubborn, with a moderate energy level and an easy-care coat. These days, heâ€™s less likely to hunt lions and more likely to hunt a soft spot on the sofa after going jogging with you.\r', 'Rhodesian_Ridgeback.jpg'),
(9, 'Afghan Hound', 'The Afghan Hound is elegance personified. This unique, ancient dog breed has an appearance quite unlike any other: dramatic silky coat, exotic face, and thin, fashion-model build. Looks aside, Afghan enthusiasts describe this hound as both aloof and comical. Hailing from Afghanistan, where the original name for the breed was Tazi, the Afghan is thought to date back to the pre-Christian era and is considered one of oldest breeds.\r', 'Afghan_Hound.jpg'),
(10, 'Basset', 'The Afghan Hound is elegance personified. This unique, ancient dog breed has an appearance quite unlike any other: dramatic silky coat, exotic face, and thin, fashion-model build. Looks aside, Afghan enthusiasts describe this hound as both aloof and comical. Hailing from Afghanistan, where the original name for the breed was Tazi, the Afghan is thought to date back to the pre-Christian era and is considered one of oldest breeds.\r', 'Basset.jpg'),
(11, 'Beagle', 'The Afghan Hound is elegance personified. This unique, ancient dog breed has an appearance quite unlike any other: dramatic silky coat, exotic face, and thin, fashion-model build. Looks aside, Afghan enthusiasts describe this hound as both aloof and comical. Hailing from Afghanistan, where the original name for the breed was Tazi, the Afghan is thought to date back to the pre-Christian era and is considered one of oldest breeds.\r', 'Beagle.jpg'),
(12, 'Bloodhound', 'The Bloodhoundâ€™s ancestors were created in medieval France to trail deer and boar. Today, heâ€™s a highly active and intelligent dog breed whose keen sense of smell has found him a special place in law enforcement and search and rescue. His fans love him for his sweet nature and unique appearance.\r', 'Bloodhound.jpg'),
(13, 'Bluetick', 'Fast and muscular, the Bluetick dog breed stands out for his striking coat. He has a pleasantly pleading expression and a big bawl mouth â€” meaning he has a long, drawn out bark. Although heâ€™s a hunter first and foremost, the Bluetick can be a fine housedog and loves his people.\r', 'Bluetick.jpg'),
(14, 'Black', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Black.jpg'),
(15, 'Walker Hound', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Walker_Hound.jpg'),
(16, 'English Foxhound', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'English_Foxhound.jpg'),
(17, 'Redbone', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Redbone.jpg'),
(18, 'Borzoi', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Borzoi.jpg'),
(19, 'Irish Wolfhound', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Irish_Wolfhound.jpg'),
(20, 'Italian Greyhound', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Italian_Greyhound.jpg'),
(21, 'Whippet', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Whippet.jpg'),
(22, 'Ibizan_Hound', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Ibizan_Hound.jpg'),
(23, 'Norwegian Elkhound', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Norwegian_Elkhound.jpg'),
(24, 'Otterhound', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Otterhound.jpg'),
(25, 'Saluki', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Saluki.jpg'),
(26, 'Scottish Deerhound', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Scottish_Deerhound.jpg'),
(27, 'Weimaraner', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Weimaraner.jpg'),
(28, 'Staffordshire Bullterrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Staffordshire_Bullterier.jpg'),
(29, 'American Staffordshire Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'American_Staffordshire_Terrier.j'),
(30, 'Bedlington Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Bedlington_Terrier.jpg'),
(31, 'Border Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Border_Terrier.jpg'),
(32, 'Kerry Blue Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Kerry_Blue_Terrier.jpg'),
(33, 'Irish Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Irish_Terrier.jpg'),
(34, 'Norforlk Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Norforlk_Terrier.jpg'),
(35, 'Norwich_Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Norwich_Terrier.jpg'),
(36, 'Yorkshire_Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Yorshire_Terrier.jpg'),
(37, 'Wire', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Wire.jpg'),
(38, 'Lakeland Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Lakeland_Terrier.jpg'),
(39, 'Sealyham Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Sealyham_Terrier.jpg'),
(40, 'Airedale', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Airedale.jpg'),
(41, 'Cairn', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Cairn.jpg'),
(42, 'Austrialian Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Austrialian_Terrier.jpg'),
(43, 'Dandie Dinmont', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Dandie_Dinmont.jpg'),
(44, 'Boston Bull', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Boston_Bull.jpg'),
(45, 'Miniature Schnauzer', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Miniature_Schnauzer.jpg'),
(46, 'Giant Schnauzer', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Giant_Schnauzer.jpg'),
(47, 'Standard Shnauzer', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Standard Shnauzer.jpg'),
(48, 'Scotch Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Scotch_Terrier.jpg'),
(49, 'Tibetan Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Tibetan_Terrier.jpg'),
(50, 'Silky Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Silky_Terrier.jpg'),
(51, 'Soft', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Soft.jpg'),
(52, 'West Highland White Terrier', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'West_Highland_White_Terrier.jpg'),
(53, 'Lhasa', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Lhasa.jpg'),
(54, 'Flat', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Flat.jpg'),
(55, 'Curly', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Curly.jpg'),
(56, 'Golden Retriever', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Golden_Retriever.jpg'),
(57, 'Labrador Retriever', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Labrador_Retriever.jpg'),
(58, 'Chesapeake Bay retriever', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Chesapeake_Bay_Retriever.jpg'),
(59, 'German Short', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'German_Short.jpg'),
(60, 'Vizsla', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Vizla.jpg'),
(61, 'English Setter', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'English_Setter.jpg'),
(62, 'Irish Setter', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Irish_Setter.jpg'),
(63, 'Gordon Setter', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Gorder_Setter.jpg'),
(64, 'Brittany Spaniel', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Brittany_Spaniel'),
(65, 'Clumber', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Clumber.jpg'),
(66, 'English Springer', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'English_Springer.jpg'),
(67, 'Welsh Springer Spaniel', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Welsh_Springer_Spaniel.jpg'),
(68, 'Cocker Spaniel', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Cocker_Spaniel.jpg'),
(69, 'Sussex Spaniel', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Sussex_Spaniel.jpg'),
(70, 'Irish Water Spaniel', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Irish_Water_Spaniel.jpg'),
(71, 'Kuvasz', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Kuvasz.jpg'),
(72, 'Schipperke', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Schipperke.jpg'),
(73, 'Groenendael', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Groenendael.jpg'),
(74, 'Malinois', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Malinois.jpg'),
(75, 'Briard', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Briard.jpg'),
(76, 'Kelpie', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'kelpie.jpg'),
(77, 'Komondor', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Komondor.jpg'),
(78, 'Old English Sheepdog', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Old_English_Sheepdog'),
(79, 'Shetland Sheepdog', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Shetland Sheepdog'),
(80, 'Collie', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Collie.jpg'),
(81, 'Border Collie', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Border_Collie.jpg'),
(82, 'Bouvier Des Flandres', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Bouvier_Des_Flandres.jpg'),
(83, 'Rottweiler', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Rottweiler.jpg'),
(84, 'German Shepherd', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'German_Shepherd.jpg'),
(85, 'Doberman', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Doberman.jpg'),
(86, 'Miniature Pinscher', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Miniature_Pinscher.jpg'),
(87, 'Greater Swiss Mountain Dog', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Greater_Swiss_Mountain_Dog.jpg'),
(88, 'Bernese Mountain Dog', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Bernese_Mountain_Dog.jpg'),
(89, 'Appenzeller', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Appenzeller.jpg'),
(90, 'EntleBucher', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'EntleBucher.jpg'),
(91, 'Boxer', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Boxer.jpg'),
(92, 'Bull Mastiff', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Bull_Mastiff.jpg'),
(93, 'Tibetan Mastiff', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Tibetan_Mastiff.jpg'),
(94, 'French Bulldog', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'French Bulldog.jpg'),
(95, 'Great Dane', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Great_Dane.jpg'),
(96, 'Saint Bernard', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Saint_Bernard.jpg'),
(97, 'Eskimo Dog', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Eskimo_Dog.jpg'),
(98, 'Malamute', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Malamute.jpg'),
(99, 'Siberian Husky', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Siberian_Husky.jpg'),
(100, 'Affenpinscher', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Affenpinscher.jpg'),
(101, 'Basenji', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Basenji.jpg'),
(102, 'Pug', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Pug.jpg'),
(103, 'Leonberg', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Leonberg.jpg'),
(104, 'Newfoundland', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Newfoundland.jpg'),
(105, 'Great Pyrenees', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Great_Pyrenees.jpg'),
(106, 'Samoyed', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Samoyed.jpg'),
(107, 'Pomeranian', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Pomeranian.jpg'),
(108, 'Chow', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Chow.jpg'),
(109, 'Keeshond', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Keeshond.jpg'),
(110, 'Brabancon', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Brabancon.jpg'),
(111, 'Pembroke', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Pembroke.jpg'),
(112, 'Cardigan', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Cardigan.jpg'),
(113, 'Toy Poodle', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Toy_Poodle.jpg'),
(114, 'Miniature Poodle', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Miniature_Poodle.jpg'),
(115, 'Standard Poodle', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Standard_Poodle.jpg'),
(116, 'Mexican Hairless', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Mexican_Hairless');
INSERT INTO `dog_breeds` (`breed_id`, `breed_name`, `breed_description`, `breed_image`) VALUES
(117, 'Dingo', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Dingo.jpg'),
(118, 'Dhole', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Dhole.jpg'),
(119, 'African Hunting Dog', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'African_Hunting_Dog.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `dog_breeds`
--
ALTER TABLE `dog_breeds`
  ADD PRIMARY KEY (`breed_id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
