-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 29, 2018 at 11:00 AM
-- Server version: 10.1.21-MariaDB
-- PHP Version: 7.1.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sp_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `dog_breeds`
--

CREATE TABLE `dog_breeds` (
  `breed_id` int(11) NOT NULL,
  `breed_name` varchar(32) NOT NULL,
  `breed_description` varchar(1000) NOT NULL,
  `breed_image` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `dog_breeds`
--

INSERT INTO `dog_breeds` (`breed_id`, `breed_name`, `breed_description`, `breed_image`) VALUES
(0, 'Chihuahua', 'The Chihuahua dog breed‘s charms include his small size, outsize personality, and variety in coat types and colors. He’s all dog, fully capable of competing in dog sports such as agility and obedience, and is among the top 10 watchdogs recommended by experts. He loves nothing more than being with his people and requires a minimum of grooming and exercise.', 'Chihuahua.jpg'),
(1, 'Japanese Chin/Spaniel', 'The Japanese Chin dog breed hails from Asia, where he has been prized as a companion for more than a thousand years. He was a popular member of Chinese and Japanese imperial courts, and it was in Japan that his distinctive look was developed. This breed is elegant and dainty, mild-mannered and playful.', 'Japanese_Spaniel.jpg'),
(2, 'Maltese', 'A dog breed who’s gentle and fearless, the Maltese greets everyone as a friend. His glamorous white coat gives him a look of haughty nobility, but looks can be deceiving. This is a sprightly, vigorous dog who excels not only as a companion but also as a therapy dog and competitor in such dog sports as agility, obedience, rally, and tracking. But most of all, he loves to be with his people.', 'Maltese.jpg'),
(3, 'Pekinese', 'Pekinese were dogs bred for centuries to be the cherished companions of the imperial family of China. Today they are still cherished family companions and show dogs who greet everyone they meet with dignity and grace.', 'Pekinese.jpg'),
(4, 'Shih-Tzu', 'His name means little lion, but thereâ€™s nothing fierce about this dog breed. The Shih Tzu is a lover, not a hunter. Bred solely to be a companion, the Shih Tzu is an affectionate, happy, outgoing housedog who loves nothing more than to follow his people from room to room. In recent years, however, owners have started taking the Shih Tzu off their laps and into dog sports, training him for obedience, rally, and agility competitions.\r', 'Shih_Tzu.jpg'),
(5, 'Blenheim Spaniel', 'Although heâ€™s born to be a companion, the Blenheim Spaniel, also called Cavalier King Charles Spaniel dog breed, retains the sporty nature of his spaniel ancestors. If heâ€™s not sitting on a lap or getting a belly rub, nothing makes him happier than to flush a bird and then attempt to retrieve it. One of the largest of the toy breeds, heâ€™s often as athletic as a true sporting breed and enjoys hiking, running on the beach, and dog sports such as agility, flyball and rally. Some have even shown their prowess as hunting dogs. The more restful members of the breed find success as family friends and therapy dogs.\r', 'Blenheim_Spaniel.jpg'),
(6, 'Papillon', 'The Papillon dog breed descends from the toy spaniels that are frequently portrayed in paintings by the Old Masters, from as far back as the 16th century. Heâ€™s highly active and is a wonderful competitor in agility and obedience. His sparkling personality makes him a favorite of all who meet him.\r', 'Papillon.jpg'),
(7, 'Toy Terrier', 'Originally created as smaller versions of their larger Smooth Fox Terrier dog breed ancestors, Toy Fox Terriers have been used for a variety of tasks, serving as ratters on farms and as hunters of small game such as squirrel. They have been successful circus dogs and performers and their intelligence helps them to do well in obedience and agility competitions. Their most important purpose, however, is to be a loyal, loving, and devoted companion that amuses and entertains their families\r', 'Toy_Terrier.jpg'),
(8, 'Rhodesian Ridgeback', 'This handsome dog breed was created in Africa to be a versatile hunter and home guardian. Heâ€™s smart but sometimes stubborn, with a moderate energy level and an easy-care coat. These days, heâ€™s less likely to hunt lions and more likely to hunt a soft spot on the sofa after going jogging with you.\r', 'Rhodesian_Ridgeback.jpg'),
(9, 'Afghan Hound', 'The Afghan Hound is elegance personified. This unique, ancient dog breed has an appearance quite unlike any other: dramatic silky coat, exotic face, and thin, fashion-model build. Looks aside, Afghan enthusiasts describe this hound as both aloof and comical. Hailing from Afghanistan, where the original name for the breed was Tazi, the Afghan is thought to date back to the pre-Christian era and is considered one of oldest breeds.\r', 'Afghan_Hound.jpg'),
(10, 'Basset', 'The Basset Hounds are the only living descendents of our earliest scenthounds, and as a smooth, short-coated dog, the Basset Hound has a long, heavy body with wrinkly-cute, short stout legs. This Basset form has been developed over centuries for its owners to follow the dog on foot with the dog leading, as they hunt through dense cover for badgers, rabbits, and hares, allowing the hound to hunt with its famous sense of smell. ', 'Basset.jpg'),
(11, 'Beagle', 'The Beagle is an easy-to-care for dog, as it is a small and sturdy hound that is squarely built and a hardy breed. The Beagle can come in a variety of colors including black and tan, orange and white, and most commonly a tri-color. The Beagle\'s coat is hard and of medium length; hair grows steadily and rarely needs trimming. ', 'Beagle.jpg'),
(12, 'Bloodhound', 'The Bloodhoundâ€™s ancestors were created in medieval France to trail deer and boar. Today, heâ€™s a highly active and intelligent dog breed whose keen sense of smell has found him a special place in law enforcement and search and rescue. His fans love him for his sweet nature and unique appearance.\r', 'Bloodhound.jpg'),
(13, 'Bluetick', 'Fast and muscular, the Bluetick dog breed stands out for his striking coat. He has a pleasantly pleading expression and a big bawl mouth â€” meaning he has a long, drawn out bark. Although heâ€™s a hunter first and foremost, the Bluetick can be a fine housedog and loves his people.\r', 'Bluetick.jpg'),
(14, 'Black and Tan Coonhound', 'The Black and Tan Coonhound is classified as a working dog. Different from most breeds, the Black and Tan Coonhound hunts by scent only. Commonly used to run coons up trees, they will also chase their prey down trails. Been highly resistant to the most rigorous days of winter and also capable of withstanding high summer temperatures, it makes a great companion for the die hard outdoorsman. It will claim any kind of enviroment as it\'s own, no matter how rocky, hilly or bushy it might be. As most of the large hunting breeds, the Coonhound may be trained to hunt larger prey as well.', 'Black_And_Tan_Coonhound.jpg'),
(15, 'Walker Hound', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Walker_Hound.jpg'),
(16, 'English Foxhound', 'The English Foxhound is a dog breed with earnest eyes that just seem to connect with yours as soon as you come upon it. Intelligent and able, the English Foxhound is a dog that\'s easily identifiable. Athletic looking, this dog breed has a clean look that has a wide skull and a long muzzle. The strong hindquarters and the long neck allow this breed to look graceful and strong at the same time. But this only makes sense as they are hunting dogs by nature.', 'English_Foxhound.jpg'),
(17, 'Redbone', 'The Redbone Coonhound is a medium sized lean and muscular breed of dog bred for hunting. They were originally developed for hunting raccoons, and are faster to tree a coon than any other coonhound. In addition to their expertise at tracking raccoons, they also excel in hunting bear, cougar and bobcat. They are a very coordinated and agile dog that allows them to be versatile enough to cover every type of ground from the swamplands to the mountains and are also used as water dogs. The Redbone Coonhound is probably one of the best all around hunting dogs. Their strength and endurance make it easy for them to cover all kinds of terrain, even jumping over fences up to 5 feet high.', 'Redbone.jpg'),
(18, 'Borzoi', 'The Borzoi is an excellent dog. This type of dog is also known as a Russian Wolfhound. Their bodies are much the same as that of a Greyhound in size and structure. These are amazing dogs for their beauty but also for their temperament. They fit within the realm of a dog that can be appreciated by anyone that is looking for one. For those with a lot of room, the Borzoi will fit right into your family unit.', 'Borzoi.jpg'),
(19, 'Irish Wolfhound', 'The Irish Wolfhound is a huge, muscular breed of dog that is bred to hunt. The Irish Wolfhound gets its name from its purpose, which was wolf hunting. This dog is one of the tallest breeds in the world. They are known for being like a huge gentle giant. They can reach the size of a small pony and when on their hind legs can reach 7 feet tall. They move a very swift pace and are known for having excellent eyesight.', 'Irish_Wolfhound.jpg'),
(20, 'Italian Greyhound', 'The Italian Greyhound is very similar to a fine-boned Greyhound but with some distinct qualities that differentiate from the latter breed. The Italian Greyhound has a thin coat and long head with a thinning, gradually pointed muzzle. These dogs have fine narrow ears that fold back on the head, but they will rise to a perpendicular state when the dog is alert, anxious, or excited. The abdomen is usually tucked in and the back is arched; the dog has a dark nose and thin lips with a generally healthy scissors bite. ', 'Italian_Greyhound.jpg'),
(21, 'Whippet', 'The Whippet is a medium sized, active and playful shorthaired dog that is part of the sighthound family. They look like a greyhound, but are a breed of their own. They are gentle and quiet dogs that make great all around family pets. They become very attached to their family members, including the children and enjoy spending most of their day sleeping. Some Whippets are prone to \'excessive greeting disorder, which occurs when a dog will jump, bark, and howl when his owners return from any absence of 10 minutes for longer. This can be dangerous if you have young children in the home, so you may want to crate your Whippet while you are gone, so the family can enter the home safely before uncrating him.', 'Whippet.jpg'),
(22, 'Ibizan_Hound', 'The Ibizan Hound is an athletic and agile hound that is recognized for its long, arched neck, long wedge-shaped head, and amber eyes. The eyes of the Ibizan Hound are generally quite large and amber in color. The hound has triangular ears which stand straight up when the dog is alert, and the teeth of this breed are very healthy.', 'Ibizan_Hound.jpg'),
(23, 'Norwegian Elkhound', 'The Norwegian Elkhound is a compact and muscular medium sized dog that is very like a spitz breed in appearance and somewhat like a hound in temperament and hunting ability. The Norwegian Elkhound gives the appearance of athletic ability, power and intelligence while still being an excellent dog for families.', 'Norwegian_Elkhound.jpg'),
(24, 'Otterhound', 'The Otterhound is a large dog with a rough coat and classic shaggy face. It has bushy eyebrows and a wide head. The neck is muscular and it has a noticeable dewlap. The Otterhound is a large, strong breed and has a woolly undercoat. The most common colors include black and tan grizzle. While the muzzle and snout are well-proportioned, the lips are thick and pendant-shaped. The dense undercoat is a noticeable trait of this breed, and it often has black markings.', 'Otterhound.jpg'),
(25, 'Saluki', 'The Saluki is a medium-sized breed with a long and regal history. This breed is considered by many to be the oldest in the world. The royal dog of Egypt, the Saluki originated in the Middle East where their bodies have been found mummified alongside Pharaohs. Their pictures have been found on Egyptian tombs that date from 2100 BC.', 'Saluki.jpg'),
(26, 'Scottish Deerhound', 'The Scottish Deerhound is a fairly unfamiliar breed to most Americans. In fact, the American Kennel Club places this dog breed near the very bottom of the list in terms of numbers of dogs registered in the This is a large and graceful dog that is gentle and sweet. These dogs make wonderful hunting dogs or family pets, but they must be given plenty of exercise. They are very intelligent dogs and can learn coursing and agility exercises quite easily. These dogs do very well with children, particularly when the dog is older. Young Scottish Deerhounds often do not know their strength and size and may inadvertently hurt a little one. They bark very little, and have a somewhat unusual howl sound.', 'Scottish_Deerhound.jpg'),
(27, 'Weimaraner', 'An elegant and noble hunting dog with the look of an aristocrat, combined with kind and gentle features, the Weimaraner is very athletic with a total balance of body form that gives it the highest star quality look. The tallest of the gundog groups, a major requirment of this beautiful breed is that it works in the field--regardless of its background in show or hunting stock--with great speed and endurance. Any faults of this dog that interferes with its working ability are extremely penalized.', 'Weimaraner.jpg'),
(28, 'Staffordshire Bullterrier', 'The Staffordshire Bull Terrier is a smooth-coated dog in variety of different colors. Although very muscular, SBTs should be active and agile. The Body should be compact and muscular, with a level top line and short loins. The length from withers to tail set should be the equal length as from withers to the ground. These dogs may small in size, but they possess great strength. ', 'Staffordshire_Bullterrier.jpg'),
(29, 'American Staffordshire Terrier', 'The stocky and muscular look of the American Staffordshire Terrier makes this particular dog breed not only impressive, but also slightly intimidating to strangers and other dogs. The strength of this agile dog is apparent from the outer appearance. With a powerful and broad head structure, the short muzzle is accentuated by a strong set jawbone. The ears of the American Staffordshire Terrier are often short and cropped.', 'American_Staffordshire_Terrier.jpg'),
(30, 'Bedlington Terrier', 'Bedlington Terriers are medium-sized dogs covered in lightly-colored fur, sometimes patched in two colors. They bear a passing resemblance to Whippets in their shape (with no distinct stop between the crown of their heads and their nose), and their curling, dense coat gives them a fairly non-threatening look, something like a tiny cloud with two eyes, claws, and a panting pink tongue.', 'Bedlington_Terrier.jpg'),
(31, 'Border Terrier', 'With a recent number of appearances in movies and TV, the Border Terrier is once again regaining the popularity it has held at different time periods throughout history. It has become one of the most adored breeds of the canine world thanks to its intelligence and head to tail characteristic charm. The Border Terrier, with its shaggy tan coat, not only perfectly fits the image that comes to mind when imagining a dog, it also fits the many portrayals throughout culture in children\'s books and stories. ', 'Border_Terrier.jpg'),
(32, 'Kerry Blue Terrier', 'The Kerry Blue Terrier has been rightfully named after the County of Kerry in South West Ireland. The dog has often been called the Irish Blue Terrier to give it its territorial designation, and has been common in the County Kerry region for centuries. Known to be a working dog, this dog has often been used to herd cattle and sheep, and works as a guard dog in most countryside farms and even households.', 'Kerry_Blue_Terrier.jpg'),
(33, 'Irish Terrier', 'The Irish Terrier is a very distinguished looking breed. This medium-sized, well-proportioned animal looks somewhat like the Wirehaired fox terrier and is sometimes mistaken for that breed', 'Irish_Terrier.jpg'),
(34, 'Norfolk Terrier', 'In the beginning, the Norfolk terrier was raised to be a working dog. The breed, small enough to chase down even smaller vermin, is efficiently stocky enough to hold its own. A mere 10 to 12 inches (or approximately 25 centimeters) at the shoulder, its petite stature allowed for getting into and under the smallest of spaces, including burrows when necessary. At optimal health and condition, the dog will weigh in at 10-12 pounds (up to 5 1/2 kg). Males and females are of comparable size and stature, with females weighing only slightly less than males. No longer used for its original purpose, the dog makes a perfect small sized pet for homes with a limited amount of space.', 'Norkfolk_Terrier.jpg'),
(35, 'Norwich_Terrier', 'The Norwich Terrier is one of the smaller terriers, standing only about ten inches tall at the withers. It has a distinctive double coat, which can appear in several hues (although red is by far the most common.) The dogs are known for their excellent ratting skills, as well as for their extremely companionable personalities, high energy levels, and generally willful and intelligent terrier personalities. The breed is not to be confused with the Norfolk Terrier, who are closely related but who differ in terms of ear shape: the Norfolk Terrier has drooping ears, while the Norwich Terrier\'s ears are always \"pricked\" and straight.', 'Norwich_Terrier.jpg'),
(36, 'Yorkshire Terrier', 'The Yorkie\'s long, glossy coat goes all the way to the ground and requires daily brushing. The hair on its head is usually tied up or parted down the middle all the way to the tail flowing straight and evenly on both sides. It has steal blue on the body and tail but tan everywhere else. There maybe be an almost gold color around the face. The head is small and somewhat flat. The muzzle isn\'t very long with a black nose. Eyes are medium sized and dark in color. The ears are small, V-shaped and carried erect. They are not too far apart, covered with short hair, and very deep in color usually a rich tan. ', 'Yorkshire_Terrier.jpg'),
(37, 'Wire-Haired Fox Terrier', 'The Wire Fox Terrier is an elegant and well built dog. It has a lot of strength compacted into a small structure. They are hunting and tracking dogs by nature and therefore are built with agility and many other hunting qualities. They have strong well developed jaws and teeth, eagerness, and physical strength. Above all else though, they pack a lot of courage. These are considered its weapons of attack. The eyes are dark, small, and deep set. Their neck is thick and extremely muscular. The skull is flat, tapering, and narrow skull. The ears are v-shaped and fold forward. The hair on the upper and lower jaws should only be long enough to give the impression of strength.', 'Wire_Haired_Fox_Terrier.jpg'),
(38, 'Lakeland Terrier', 'The Lakeland Terrier is a small sized terrier breed with a jaunty look and an intelligent expression. The face is long and rectangular in profile with smaller ears that fold over at the tips. The jaws and muzzle of the Lakeland Terrier are strong and square looking with a slight beard that adds to their unique appearance. The face is rather elongated giving a balanced appearance to the profile of the breed. The eyes are dark brown or hazel and are often partially obscured by the curly hair on the face.', 'Lakeland_Terrier.jpg'),
(39, 'Sealyham Terrier', 'The Sealyham terrier is a small dog that thinks it is a big dog. On average, the Sealyham terrier stands about 10 1/2 inches at the shoulder and normally weighs approximately 24 pounds at maturity. Other than markings on the head, the Sealyham should be all white but in some cases it is yellowish-white. The healthy coat is a double coat with a soft and dense undercoat and an outer coat that is hard, wiry and weather-resistant', 'Sealyham_Terrier.jpg'),
(40, 'Airedale Terrier', 'The Airedale Terrier is a large and very lively terrier that is often known as the \"king of terriers\". They are excellent companion dogs as well as hunting, agility, obedience and even police and military dogs. They can be very playful and attentive to their owners but can also be serious workers, an excellent combination for a great all-round dog. ', 'Airedale.jpg'),
(41, 'Cairn Terrier', 'The Cairn Terrier is a small athletic looking dog that has a mischievous and intelligent look. Often their face is described as being almost fox-like in appearance with sharp pointed ears that are set relatively high on the head. The ears are always carried erect and the bushy topknot and longer hairs on the ears give a softened outline to the head. The muzzle is strong looking but not square and is somewhat pointed in appearance. The face has a definite stop between the deep set brown or hazel eyes that are framed by bushy eyebrows.', 'Cairn.jpg'),
(42, 'Australian Terrier', 'These little dogs are essentially small terrier hybrids that were bred for the very specific purpose of killing the local rats and snakes in 19th century Australia. As such, the Aussie\'s ancestor dogs are generally those terriers that originate from the British Isles just as the European migrants did.', 'Australian_Terrier.jpg'),
(43, 'Dandie Dinmont Terrier', 'This dog is long and short, like a dachshund, but with the face and temperament of a terrier. Originally bred in southern Scotland, this breed has been the scourge of vermin for several hundred years while being a happy and fun loving delight for human companions. ', 'Dandie_Dinmont.jpg'),
(44, 'Boston Bull', 'Boston terriers are compact dogs. They have big flat heads with no wrinkles, wide-set dark eyes, small erect ears, and a wide flat snout with an ample black nose. Their frame is boxy, with a nice muscular build, and a short stubby tail. The fur of a Boston is fine, short, and thin. The neck is slightly arched, leading down to a broad chest. Their face shows a lot of personality and intelligence. A Boston\'s limbs are straight and well pronounced, and close to the same size as his body. ', 'Boston_Bull.jpg'),
(45, 'Miniature Schnauzer', 'The Miniature Schnauzer is a small robust dog, nearly square in proportion. This dog is literally made up of rectangles. The head is rectangular in shape, which is accentuated by the long, thick beard, and heavy eyebrows. The muzzle is parallel to, and as long as, the topskull and ending in a blunt wedge. His teeth should meet in a scissors bite, with no signs of an overbite. The eyes should be deep-set, small, dark brown, and oval shaped.', 'Miniature_Schnauzer.jpg'),
(46, 'Giant Schnauzer', 'The Giant Schnauzer is a dog with a square build, a short, slightly arched back that slopes down a little. The head is about half as long as the back from withers to tail. The muzzle and top of the head should be parallel. The nose is large and black. Eyes are dark brown and oval shaped. The teeth should make a scissor bite and there should be no under or over bite. In some countries, where permissible, the ears are cropped. Ears should stand sharp and erect. The tail is set on high and carried erect, and where permissible docked at about the second or third joint.', 'Giant_Schnauzer.jpg'),
(47, 'Standard Schnauzer', 'The Standard Schnauzer is a distinctive looking dog with its beard and whiskers, bushy eyebrows and overall impression of power and dignity. The Standard is the actual original size of all Schnauzer\'s and is actually a medium size breed that gives of an impression of a much larger and more powerful dog. Usually described as a square shape in both body and head, the Standard Schnauzer is very muscular and athletic looking without appearing heavy or cobby.', 'Standard_Schnauzer.jpg'),
(48, 'Scotch Terrier', 'The Scottish Terrier, also known as the Aberdeen Terrier, is a strong and sturdy breed of little dog that is often called just the Scottie. He has a distinctive and unique shape and profile, which the dog is known for. He is one of five different breeds of terrier that came from Scotland, with the other four being Skye, Cairn, Dandie Dinmont and West Highland Whiter Terriers. George the fourth, the Earl of Dumbarton gave them the nickname, little diehard\" in the 19th century because of their bravery and perseverance.', 'Scotch_Terrier.jpg'),
(49, 'Tibetan Terrier', 'To any dog enthusiast, the word terrier conjures up a certain image: gruff, intelligent, excitable, bred for the killing of rats and vermin. One hears the name \"Tibetan Terrier\" and one assumes that the same holds true for this fairly unknown breed.', 'Tibetan_Terrier.jpg'),
(50, 'Silky Terrier', 'The Silky Terrier dog breed exemplifies the expression \'small dog, big personality.\' Weighing just eight to 10 pounds when full grown, he’s tough and confident, perhaps because of his heritage as a hunter of small prey. Beneath the feistiness, however, is a loving companion dog who loves to stick close to his person.', 'Silky_Terrier.jpg'),
(51, 'Soft Coated Wheaten Terrier', 'The Soft Coated Wheaten Terrier is a medium sized dog that is very squarely and solidly built without appearing to be heavy or chunky. The breed is very athletic with a good bone structure through the legs and body providing strength as well as the ability to move quickly through all types of terrain. The legs are relatively long for the size of the dog and well furnished, making them appear a bit larger than they actually are. ', 'Soft_Coated_Wheaten_Terrier.jpg'),
(52, 'West Highland White Terrier', 'Known to many people as the \"Westie,\" this breed is a small dog but is very well balanced and hardy. Always able to exhibit good showmanship when exhibited, especially when they are groomed properly, they are very elegant looking with a beautiful white coat and bright dark button eyes.\n', 'West_Highland_White_Terrier.jpg'),
(53, 'Lhasa Apso', 'The Lhasa Apso is an ancient, small breed which has beautiful dark eyes that are mysteriously appealing. Their long bodies sit atop short legs that make for a very hardy little dog. They have long, coarse coats that come in many colors and patterns that is neither silk nor wooly. ', 'Lhasa.jpg'),
(54, 'Flat Coated Retriever', 'The Flat Coated Retriever is a noble and sturdy dog, and stands strong as a gundog from Britain. It has been trained and bred to work on both land and, and these dogs are exceptional family companions as well. The Flat Coated Retriever has a strong, muscular jaw and long muzzle. It is a unique breed with its one-piece backskull and muzzle, and often carries a friendly and intelligent expression. The ears are pendant-shaped and are fairly small. They lie closely to the back of the skull and the dogs have a well-arched neck. The top line of the dog is strong and straight, while the back of the dog\'s head is angulated.', 'Flat_Coated_Retriever.jpg'),
(55, 'Curly Coated Retriever', 'Curly-Coated Retriever can be described as a large, hardy, and athletic looking dog. They have a tight curly coat which will protect them from debris and injuries when they are out in the brush. Their tight curls even extend to their small ears, back of the neck, and tail. Only the face, the front of the legs, and the hocks are smooth. They should be strong, agile, while remaining elegant.\n', 'Curly_Coated_Retriever.jpg'),
(56, 'Golden Retriever', 'The Golden Retriever is divided into two groups, primarily based on their appearance. The first group is the English, and they are shorter, bigger-boned, and tend to have longer coats that are lighter in color. The American group tends to be lanky with longer limbs, and have characteristics that are more similar to the origins of their breed.', 'Gold.jpg'),
(57, 'Labrador Retriever', 'The Labrador Retriever is one of the most popular and easily-identifiable dogs in the world. The dog is reasonably large, standing at about two feet at the shoulders and with an extremely heavy and muscular body. Labs have floppy ears, longish noses, long legs relative to their stocky bodies, and distinctive otter-like tails that help them to steer their bodies when swimming. They come in three basic color variations--chocolate, black, and yellow--with a wide variety of shades and hues within those basic colors, anywhere from a foxlike red to a nearly-white shade of lemon.', 'Labrador_Retriever.jpg'),
(58, 'Chesapeake Bay retriever', 'The Chesapeake Bay Retriever is a large, muscular dog that is sturdy and very solid looking even as a puppy. They come in various shades of brown ranging from a lighter tan or straw color through to a deep brown or mahogany color. The coat is rather short and may be somewhat wavy, especially down the back and around the neck and shoulder area. The Chesapeake Bay Retriever has a unique double coat that is slightly oily to the touch on both the inner and outer layers.', 'Chesapeake_Bay_Retriever.jpg'),
(59, 'German Short Haired Pointer', 'A structurally correct German Shorthaired Pointer is lean, well-balanced, athletic, and graceful, yet powerful, and of medium size. They have moderately floppy ears, soft to the touch and set high on the head. The muzzle is long and broad, making it easier to retrieve game. The muzzle should never be pointed. Eyes are generally dark brown in color, with yellow being a fault. The eyes should not be set too close and should be almond shaped instead of round. The nose should also be brown and as large as possible, with nostrils broad and well opened.', 'German_Short_Haired_Pointer.jpg'),
(60, 'Vizsla', 'The Vizsla is very muscular, sleek and very athletic looking medium sized dog that is used for hunting as well as a companion pet. They are very balanced in appearance and have a typical hunting dog alertness, energy and eagerness about them at all times. The Vizsla is always a beautifully coppery gold to rust color and has a shorter coat, although it is very dense and thick.', 'Vizsla.jpg'),
(61, 'English Setter', 'The English Setter was bred for elegance. The dogs are lean, with powerful chests sloping back to the smooth, tense lines of legs and feet, the ready tail, and the powerful muscles. An extra splash of feathering on the Setter\'s smooth coat and a distinctive \"belton\" bi-colored (or tri-colored coat) just adds an extra touch of visibility and an extra touch of class to these already aristocratic, sleek, and intelligent dogs.', 'English_Setter.jpg'),
(62, 'Irish Setter', 'The Irish Setter is a long, lean looking dog that is very athletic and energetic looking without appearing hyperactive or rambunctious. The overall appearance of the breed is one of grace and agility as well as intelligence and excellent disposition. The head of the Irish Setter is rather long with a definite stop between the eyes and the muzzle.', 'Irish_Setter.jpg'),
(63, 'Gordon Setter', 'The Gordon Setter is one of the most distinct of the setter breeds largely because of its unique coat coloration. This breed is the only setter that always has the black and tan coloration to it long, luxurious coat and furnishings. The coat may be slightly wavy but is never curly with longer hair on the ears, chest, undersides and the legs and tail. The tail is relatively long and is rather broad at the base and tapers to a very fine point. The tail is carried low naturally but will be raised higher when the dog is excited or working.', 'Gordon_Setter.jpg'),
(64, 'Brittany Spaniel', 'Many breeders do make a differentiation between the American Brittany and the French style Brittany, however, they are considered subsets of the same breed. There are some recognizable differences found. For instance, the American Brittany is taller and faster whereas the French Brittany is more \"spaniel-like\" in its smaller stature and tends to work more closely with the guns.', 'Brittany_Spaniel.jpg'),
(65, 'Clumber', 'Considered the most gentle of all the aristocratic dog breeds, this very lovable and highly intelligent Clumber Spaniel is physically a very sound and sturdy dog, with the most perspective intelligent personality of any breed available in the sporting group. Very much a family dog, this dog adores children and all family members, and is very protective toward them along with being a good mother to their own puppies. As puppies themselves, they love to play ball and fetch, from the moment they can stagger around on their pudgy little legs and put things in their mouth--they and children kind of go hand-in-hand.', 'Clumber.jpg'),
(66, 'English Springer', 'The name English Springer Spaniel has been used since 1900. The English Springer Spaniel is a hearty, medium sized dog. Their tails are usually docked in American lines, and undocked in European lines. There is a major divide in the two types of springers: the field bred or working springer, and the show or bench bred springer.', 'English_Springer.jpg'),
(67, 'Welsh Springer Spaniel', 'The Welsh Springer spaniel is a strong, medium-built dog with a crimson and whitish coat. The hair can be curly or flat, with lots of fur on the chest and most parts of the body. The head is fairly circular in shape. The ears are long and straight, and they are also covered with fur. The eyes can be red or black. The Welsh Springer is relatively smaller as compared to an English Springer, and relatively bigger against an English Cocker Spaniel.', 'Welsh_Springer_Spaniel.jpg'),
(68, 'Cocker Spaniel', 'The Cocker Spaniel is a smaller sized spaniel that has wonderful temperament and boundless energy. They are great dogs for families as well as single people and really love being with humans, although they can tolerate moderate lengths of time alone if they are properly exercised and attended to when the family is home. The Cocker Spaniel has a beautiful, silky medium long coat that is relatively easy to care for and maintain, even if the dog is outside. ', 'Cocker_Spaniel.jpg'),
(69, 'Sussex Spaniel', 'Sussex Spaniel is a strong, medium sized dog. In fact, the Sussex spaniel can be classified as the stockiest of all spaniels. It has a long muscular body with a wide skull. The shape of its head is rather broad and long, with a deep recess in the middle. The eyes of the Sussex spaniel are hazel in color and they bear a serene expression, probably because they are somewhat droopy', 'Sussex_Spaniel.jpg'),
(70, 'Irish Water Spaniel', 'Although the Irish Water Spaniel looks much like a standard Poodle it is not a part of the Poodle family but a part of the Spaniel family. The Irish Water Spaniel is both the largest and the rarest of the spaniel family. They are a puce, dark brown or liver color that has a purple shade to their coats. The Irish Water Spaniel has medium-long curly hair that composes much of the dogs coat. The face and back of the legs of this dog are covered in short straight hair as well as their tail, which is where the alias of rat tail dog comes from. ', 'Irish_Water_Spaniel.jpg'),
(71, 'Kuvasz', 'This very large, white, fluffy dog is one of several types of large herding and mountain dogs that have spread throughout Europe in the last few thousand years. In fact most pastoral regions in Europe and Western Asia seem to have their own breed, slightly different according to the requirements of climate and inclination. They are intelligent and hard working without fail.', 'Kuvasz.jpg'),
(72, 'Schipperke', 'The Schipperke is a breed that is largely unfamiliar to the average American. But this is a great breed for those who want a watchdog or hunter that\'s not too big. The Schipperke is a dog of Belgian origin. There has been much debate over the years as to whether Schipperke\'s are categorized as a terrier, spitz, or miniature sheepdog, though it is fairly certain that they descended from a breed of sheepdog. Many years ago, Schipperkes were also referred to as Spitzkes, Spitskes or Spits.', 'Schipperke.jpg'),
(73, 'Groenendael', 'The Groenendael is a variety of dog that is included in the Belgian Shepherd breed, but sometimes treated as a distinct breed. The Groenendael is recognized, either as a breed or a variety of the larger breed, by all major kennel clubs, such as the Kennel Club of the UK. In the American Kennel Club, it is called the Belgian Sheepdog,a term otherwise synonymous with Belgian Shepherd Dog more broadly.', 'Groenendael.jpg'),
(74, 'Malinois', 'The Belgian Malinois is a medium-sized, hard-working dog in the sheepdog family. Although it is known in the United States as Belgian Malinois, it is often classified as a variety of the Belgian Shepherd Dog. Many dog experts use the word \"square\" to describe this dog because its body is almost as long as it is tall. The Belgian Malinois is strong, muscular dog with a level back and a slope at the withers and deep chest that goes down to the elbow. It has a long tail that reaches to the hock', 'Malinois.jpg'),
(75, 'Briard', 'The Briard can be characterized as a large and muscular herding dog. In addition to the herding the Briard was also used as a guard dog. This makes the Briard a natural watch dog that has strong loyalties to its owner and family. They are very eager to please and learn tasks very quickly. Due to their history of being farm dogs they were taught many tasks. They have excellent memory for commands and are able to work independently. This independent personality does not take away from its loving and affectionate nature with its family. ', 'Briard.jpg'),
(76, 'Australian Kelpie', 'The Australian Kelpie has a compact body with well-developed limbs. Slightly longer than he is tall, he has a broad chest and firm hindquarters.The head is long and narrow. The medium length tail is low set. The short, compact feet have well arched toes. The double coat consists of a short and dense undercoat and a hard, straight and weather-repellent outer coat. ', 'kelpie.jpg'),
(77, 'Komondor', 'There is almost no mistaking the Komondor for any other breed. The Komondor is a massive dog with a proud gait and a long history of honor and pride. The Komondor worked with the Puli in ancient Hungary. The Puli would do the actual herding during the daylight hours, and the massive Komondor would guard the flock at night.', 'Komondor.jpg'),
(78, 'Old English Sheepdog', 'The Old English Sheepdog is a large and well-proportioned dog, and has become a legendary dog in England and Europe. Its body is naturally stocky, well-balanced, and muscular and the unusual topline on this dog is an important breed characteristic. The chest is broad and the brisket is deep. The forelegs are straight, and the dog has small round feet that point directly forward. The dog has a well-defined stop, and the small ears lie flat. Overall, its appearance often looks disheveled and unkempt; however, with proper grooming and care this dog can look clean and well-defined naturally.', 'Old_English_Sheepdog.jpg'),
(79, 'Shetland Sheepdog', 'The Shetland Sheepdog is a small breed that stands about 13-16 inches tall. They have long usually tricolored coats that range in colors from sable, tan, white, black and grey depending on the dog and its inherited color coat scheme. The Shetland Sheepdog is often marked closely enough to a Collie to be mistaken for a miniature Collie.', 'Shetland_Sheepdog.jpg'),
(80, 'Collie', 'Collies are medium sized dogs having a well-proportioned body. The head of collies is lean, blunted and wedge shaped which makes it appear light instead of heavy. The top of the head is flat. They have a well-formed, long, soft and round muzzle, which tapers to a black nose. The ears are in proportion to the size of their head and are 3/4 quarters ahead with the tips tilting forward. This breed has medium sized, dark, almond shaped eyes with the exception of blue merles that have blue or merle eyes', 'Collie.jpg'),
(81, 'Border Collie', 'The Border Collie is a well balanced medium-sized athletic dog, bred for working and its intelligence, with either a smooth coat or is of medium length with a thick water resistant undercoat. It rather looks like an Australian Shepherd (without the bob-tail). The muzzle tapers elegantly to the all black nose and its ears are usually half perked.', 'Border_Collie.jpg'),
(82, 'Bouvier des Flandres', 'The Bouvier des Flanders is a very large and powerful dog that has a wonderful, gentle personality and a natural enthusiasm for everything that it does. They are athletic and strong yet capable of adapting to smaller living spaces provided they have regular outdoor exercise. Originally used as a cattle dog the Bouvier des Flanders is muscular and capable of running and endurance activities as well as herding and obedience type work.', 'Bouvier_Des_Flandres.jpg'),
(83, 'Rottweiler', 'Rottweilers are black in base coat color with clearly defined tan or mahogany markings on the cheeks, muzzle, chest, legs, and eyebrows. They have a strong, powerful and muscular body. The head is broad and has a rounded forehead. The eyes are warm, dark brown and an almond shape. Ears lie flat to the head and are triangular in shape. The neck is muscular and powerful without any loose skin, sloping parallel with the back. The chest is broad and deep, reaching to elbow, with well pronounced fore chest. Back is straight and strong. Loins are squat, deep and well muscled', 'Rottweiler.jpg'),
(84, 'German Shepherd', 'The German Shepherd Dog is a very strong and alert breed. They have a noble appearance with a strong and chiseled head. They have medium sized eyes that are dark and almond shaped. Their ears are somewhat pointed and open toward the front. They stand very erect when at attention. Their skulls are sloped into a long wedge shaped muzzle. Their noses are black and they have strongly developed jaws with teeth that meet in a scissors bite.', 'German_Shepherd.jpg'),
(85, 'Doberman', 'The Doberman Pinscher is a medium sized dog with a square shaped body. They are compact and muscular, with a very strong appearance. They are powerful and capable of great speed. This is an energetic and protective dog with a regal appearance. Males look decidedly masculine and females decidedly feminine.', 'Doberman.jpg'),
(86, 'Miniature Pinscher', 'The Miniature Pinscher is a dog that looks like a smaller version of the Doberman Pinscher breed. However, the two breeds are unrelated, and, in fact, the Miniature Pinscher breed is older than the Doberman Pinscher. They are small muscular dogs with square proportions and docked tails. They have tapering narrow heads with a prominent foreface that balances with the skull. Their ears are set high on the head and stand erect; they are sometimes docked. Their eyes are oval and dark in color, with a clear and bright appearance. ', 'Miniature_Pinscher.jpg'),
(87, 'Greater Swiss Mountain Dog', 'The Greater Swiss Mountain Dog is a Dober and Draft breed and should appear as such. They have a very striking yet powerful and strong appearance. They are heavy boned and well muscled. However, despite their large and powerful structure they are very agile and needed to be to perform a plethora of tasks in a mountainous region.', 'Greater_Swiss_Mountain_Dog.jpg'),
(88, 'Bernese Mountain Dog', 'The Bernese Mountain Dog is one of the oldest, most beautiful breeds of working dog recognized by the kennel clubs of the world--yet also one of the most fragile in certain ways. In its short life, however, the dog provides its owners with a sense of beauty and loyalty not often equalled by other breeds. Berense Mountain Dogs are gentle, loyal dogs above all.', 'Bernese_Mountain_Dog.jpg'),
(89, 'Appenzeller Mountain dog', 'Variously known as the Appenzeller Mountain Dog, Appenzell Mountain Dog, and Appenzeller Sennenhunde, this bold and athletic breed enjoys romping and roughhousing, especially in the snow! This rugged and intelligent breed likes to keep busy and needs to have something to do. He is not an apartment dog. Pulling a cart or sled, herding, agility, fetching balls, playing Frisbee, and weight pulling are productive outlets for his energy.', 'Appenzeller.jpg'),
(90, 'EntleBucher Mountain Dog', 'Entlebucher Mountain Dogs are muscular, long-backed cattle dogs standing from 16 to 21 inches at the shoulder. They have short, sturdy legs; a striking black, white, and tan coat; and an attentive, friendly face. Entles are famous for their agility, balance, and boundless enthusiasm.', 'EntleBucher.jpg'),
(91, 'Boxer', 'This popular breed of dog is mid-sized, with a very square jaw and naturally floppy ears that are very often surgically altered to make them stand up. They are a naturally very intelligent breed with a characteristic short nose and slight under-bite. They have long, muscular legs and deep chests for resonant barking', 'Boxer.jpg'),
(92, 'Bull Mastiff', 'The Bullmastiff is a strong looking dog at first glance - and first impressions are correct. With a sold body frame and a powerful stance, this breed can be quite intimidating to the everyday person that encounters it. But while this stocky build appears to be awkward, the overall frame of the Bullmastiff can be quite agile.\n', 'Bull_Mastiff.jpg'),
(93, 'Tibetan Mastiff', 'This still primitive dog breed was developed centuries ago in Tibet. Originally used as guard dogs for livestock and property, Tibetan Mastiffs can still be found performing that role, but they also enjoy life as a family companion and show dog.', 'Tibetan_Mastiff.jpg'),
(94, 'French Bulldog', 'The French Bulldog is compact, sturdy, and heavily boned. He is short and cobby, with a small to medium build. The height at the withers, should be approximately the same as the length from withers to tail-set. Massive chest, with tapering hindquarters. French Bulldogs have large, rounded bat-like ears, square flat heads with a slightly domed forehead, large rounded eyes, and flat muzzle. French Bulldogs are a smooth coated breed. The French Bulldog has the appearance of an intelligent, alert, active and curious nature.', 'French_Bulldog.jpg'),
(95, 'Great Dane', 'The Great Dane is a giant breed of dog that is both regal and powerful in appearance. They have oven been considered the Apollo of dogs due to their size, strength and proud carriage. They are solidly build and very athletic although calm and reserved in their behavior. The Great Dane is often called the German Mastiff and even thought they are called a Dane, the breed was actually developed in Germany. The Great Dane is often used as companion dog, cart dog, packing dog and a watchdog.', 'Great_Dane.jpg'),
(96, 'Saint Bernard', 'The Saint Bernard is a strong and powerful dog with a very tall and muscular body and a large powerful head. They have a wide skull, with high cheek bones and a distinct furrowing of the brow. The skin of their foreheads is very wrinkled, often giving them a rather stern expression, particularly if they also possess a dark mask.', 'Saint_Bernard.jpg'),
(97, 'Eskimo Dog', 'Called \'the dog beautiful\' by his admirers, the American Eskimo Dog, or \'Eskie,\' is a striking fellow with his white coat, sweet expression, and black eyes. He’s a Nordic dog breed, a member of the Spitz family. Eskies are lively, active companion dogs who love to entertain and join in on all family activities. They are outgoing and friendly with family and friends, but reserved with strangers. Although the Eskie is a small dog — 10 to 30 pounds — he has a big-dog attitude.', 'Eskimo_Dog.jpg'),
(98, 'Alaskan Malamute', 'The Alaskan Malamute is an incredibly beautiful dog but one that has much more in store for its owner than its looks. This breed is larger, too, so size is an important consideration in selecting this pet over others. They are great pets for families that can provide for their characteristic qualities of eagerness and overpowering at times. This is a highly energetic style of dog but one that is ideal for pleasing their owners. You will need to provide enough physical activity to keep him healthy.', 'Malamute.jpg'),
(99, 'Siberian Husky', 'The Siberian Husky is a beautiful gracious animal, a dog that sees through you and knows your disposition even before he has met you. He seems arogant and princelike, not deeming every man worthing of his attention. He seems somewhat like a gentle giant, in the meaning he looks kind but still requires respect. Once accepted by a Siberian first then may you experience the loving and awsome disposition of this beautiful creature.', 'Siberian_Husky.jpg'),
(100, 'Affenpinscher', 'The Affenpinscher is a small breed of dog that has a unique personality and a stout and hardy physical appearance. The breed is known for its terrier-like hunting ability and athletic qualities, as well as its almost monkey-like face and amazing array of expressions. Although a small breed, the Affenpinscher is not fragile or frail, rather they are strong, agile and very good hunters. ', 'Affenpinscher.jpg'),
(101, 'Basenji', 'The Basenji, which originated in Africa, is a small, shorthaired and athletic dog with a smooth shiny coat and is the size of a fox terrier. They have a shiny coat of a number of different colors usually having white feet as well as white on the chest and tip of the tail. The Basenji is an elegant dog with long legs and a level back. Many think they have a perpetual worried look on their face because of the deep wrinkles in their forehead.', 'Basenji.jpg'),
(102, 'Pug', 'A Multo in Parvo, \"a lot of dog in a small space\", that has an even temperament while also being playful, outgoing, dignified, and charming. This breed is supposed to be compact, proportioned and muscular. It is supposed to be square in proportion and appearance as well. The pug is one of the largest breed in the Toy Group with a weight of 14 to 18 lbs (both sexes). The Pug shares the same origin as the Pekingese but is not related to the Bulldog.', 'Pug.jpg'),
(103, 'Leonberger', 'This jumbo-sized dog breed is a mix of Newfie, longhaired Saint Bernard, and Great Pyrenees. He needs a good deal of exercise, attention, and space, but with the right owner, he can be a friend like no other. With his lion-like looks and deep bark, he makes an intimidating watch dog.', 'Leonberg.jpg');
INSERT INTO `dog_breeds` (`breed_id`, `breed_name`, `breed_description`, `breed_image`) VALUES
(104, 'Newfoundland', 'The Newfoundland is a large, solid looking dog that is both powerful and athletic at the same time. They have a large head and a very expressive face that seems to study everything and everyone before making a move or a decision. Despite their huge size this breed is a wonderful housedog and will quickly adjust to owner routines and smaller spaces. They are very careful in small spaces and are not known to be rambunctious or high-strung, rather they are very relaxed and calm dogs. ', 'Newfoundland.jpg'),
(105, 'Great Pyrenees', 'The great, white, mountain dogs have been guarding sheep in the Pyrenees and serving in the French Royal court for hundreds of years. They have been very carefully selected to not only herd sheep, but also to protect them from any danger. They can even take on bears if necessary. ', 'Great_Pyrenees.jpg'),
(106, 'Samoyed', 'The Samoyed is naturally a working dog and should exhibit qualities of strength and alertness while remaining to be elegant and beautiful. The Samoyed cannot be long in the back because the length makes the back weak and therefore the Samoyed is useless to perform its necessary tasks. However, the females may be slightly longer in the back than the males. The body should be muscular with a deep chest and well sprung ribs.', 'Samoyed.jpg'),
(107, 'Pomeranian', 'Pomeranians are short and small toy dogs. In fact, they\'re one of the smallest dog breeds in the world. They have soft dense undercoats with an abundance of outer coat that is coarsely textured. They have heavily plumed tails that lie flat on their backs. They are medium boned and sturdy in appearance, despite their small size.', 'Pomeranian.jpg'),
(108, 'Chow', 'Standing at a foot and a half or more at the shoulder, the Chow Chow is commonly recognized for the massive amount of fur that seems to encase its body and its distinctive blue black tongue. The Chow can come in light or dark shades of red, black or tan and is also occasionally found in white. Chows also come in what is called a smooth coat.', 'Chow.jpg'),
(109, 'Keeshond', 'The Keeshond is a very small and compact dog that bears a strong resemblance to their ancestor the Samoyed. This is demonstrated in their oblique chestnut eyes, erect triangular ears, and its medium length tail that rolls over onto its back. They attract attention because of their intelligent and alert expression combined with their unique coloration and luxurious coat.', 'Keeshond.jpg'),
(110, 'Brabancon Griffon', 'Lorem ipsum dolor sit amet, copiosae tincidunt at vel, eu expetenda erroribus eum. Accusata torquatos ei vim, dolore conceptam usu ad, id augue nobis qui. Impedit imperdiet in mel, pro nulla iudicabit disputando no, dicunt theophrastus interpretaris no pro. At nibh errem probatus vim, in vim soleat placerat platonem, eum no dolor mollis praesent. Ex congue accusam epicuri duo.', 'Brabancon_Griffon.jpg'),
(111, 'Pembroke', 'The Pembroke Welsh Corgi is a very sturdy looking dog that has short but powerful legs. The long and low profile of the Pembroke Welsh Corgi is unmistakable and is unique to the Corgi breeds. There is another breed of Corgi known as the Cardigan Welsh Corgi that is almost identical to the Pembroke Welsh Corgi but has a long tail, while the Pembroke variety has a very short stumpy tail.', 'Pembroke.jpg'),
(112, 'Cardigan', 'The Cardigan Welsh Corgi is a small herding dog with a straight, weather-proof coat accented by a heavy ruff around the neck and a pair of jodphur-like tufts of fur near the hind legs. Its bone structure and general proportions are reminiscent of a Dachshund, and some breeders speculate that the Cardi has some Dachsund heritage from its largely mysterious origins (before its arrival in Wales.)', 'Cardigan.jpg'),
(113, 'Toy Poodle', 'The Toy Poodle is a very energetic, intelligent, and elegant appearing small dog. It has a beautiful dens, curly, and harsh textured coat. Most coats are solid throughout. The ears are long, wide, thickly feathered and hang close to the head. The skull is moderately rounded with a long, straight muzzle. Jaws are strong with a scissor bite. Their eyes are oval in shape, and usually dark in color', 'Toy_Poodle.jpg'),
(114, 'Miniature Poodle', 'The Poodle is a fun loving dog known for its dressed up look. You will find that there are several ways that they can be groomed, which helps to define this breed\'s characteristics. The Pet Clip may be used for dog\'s that have a short hair length. The English Saddle or Continental clip is also used with the back half of the body shaved, rings are left around the feet and the tail and tails will have pom poms.', 'Miniature_Poodle.jpg'),
(115, 'Standard Poodle', 'The Standard Poodle is a medium to large sized dog with a dense, curly coat, a long slender face and muzzle, and generally delicate stature. Poodles tend to weight much less than other breeds of similar size. Also known as the French Poodle the Standard Poodle is the largest of three recognized sizes for the poodle.', 'Standard_Poodle.jpg'),
(116, 'Mexican Hairless', 'The Xoloitzcuintli, or Xolo for short, is a hairless breed of dog, found in toy, miniature, and standard sizes. The Xolo also comes in a coated variety and coated and hairless can be born in the same litter. It is also known as Mexican hairless dog in English-speaking countries, and is one of several breeds of hairless dog.', 'Mexican_Hairless.jpg'),
(117, 'Dingo', 'Dingoes are one of the few successful cases of feral dogs thriving in the wild. And while it is illegal to keep one as a pet in its native Australia, there are some who do so anyway. The dingo is also known by several other Indigenous Australian names, including Joogong, Mirigung, Noggum, Boolomo, Papa-Inura, Wantibirri, Maliki, Kal, Dwer-da, Kurpany, Aringka, Palangamwari, Repeti and Warrigal.', 'Dingo.jpg'),
(118, 'Dhole', 'Dhole is a species of wild dog that has declined dramatically across its extensive range. It is now classified as a globally endangered species with fewer than 2,500 mature individuals remaining. In Cambodia, dholes occur in both protected areas co-managed by WWF in the Eastern Plains Landscape', 'Dhole.jpg'),
(119, 'African Hunting Dog', 'The African hunting dog, also known as African wild dog, African painted dog, painted hunting dog, or painted wolf, is a canid native to Sub-Saharan Africa. It is the largest of its family in Africa, and the only extant member of the genus Lycaon, which is distinguished from Canis by its fewer toes and its dentition, which is highly specialized for a hypercarnivorous diet. It is classified as endangered by the IUCN, as it has disappeared from much of its original range', 'African_Hunting_Dog.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `dog_breeds`
--
ALTER TABLE `dog_breeds`
  ADD PRIMARY KEY (`breed_id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
